// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw7jkWMDXqkvMQ25xQIe28kQXP06koQs8',
    appId: '1:527407476731:web:cb50e5525586de67a4e55e',
    messagingSenderId: '527407476731',
    projectId: 'shopping-app-flutter-18281',
    authDomain: 'shopping-app-flutter-18281.firebaseapp.com',
    storageBucket: 'shopping-app-flutter-18281.firebasestorage.app',
    measurementId: 'G-4LN978E614',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Vh5d6VN30rG8bsI5g9_qKK9OtFxwkjY',
    appId: '1:527407476731:android:514b62f190243577a4e55e',
    messagingSenderId: '527407476731',
    projectId: 'shopping-app-flutter-18281',
    storageBucket: 'shopping-app-flutter-18281.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK4cxKNk1RY7_HlRcBxW6-7IDfWjTGGQ4',
    appId: '1:527407476731:ios:56a8a2bb83e1e5dba4e55e',
    messagingSenderId: '527407476731',
    projectId: 'shopping-app-flutter-18281',
    storageBucket: 'shopping-app-flutter-18281.firebasestorage.app',
    iosClientId: '527407476731-ev5617jjub6n6d9t69v2mecd7b9ujbcb.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK4cxKNk1RY7_HlRcBxW6-7IDfWjTGGQ4',
    appId: '1:527407476731:ios:56a8a2bb83e1e5dba4e55e',
    messagingSenderId: '527407476731',
    projectId: 'shopping-app-flutter-18281',
    storageBucket: 'shopping-app-flutter-18281.firebasestorage.app',
    iosClientId: '527407476731-ev5617jjub6n6d9t69v2mecd7b9ujbcb.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw7jkWMDXqkvMQ25xQIe28kQXP06koQs8',
    appId: '1:527407476731:web:26596b68edc76bdfa4e55e',
    messagingSenderId: '527407476731',
    projectId: 'shopping-app-flutter-18281',
    authDomain: 'shopping-app-flutter-18281.firebaseapp.com',
    storageBucket: 'shopping-app-flutter-18281.firebasestorage.app',
    measurementId: 'G-EX8VC4N2TP',
  );

}